
### Admin mette tipi di biglietti
POST http://localhost:8082/admin/tickets/
X-XSRF-TOKEN: 224159f4-d4ed-41ff-b726-c6d7a2ad71d6
Content-Type: application/json
Cookie: XSRF-TOKEN=224159f4-d4ed-41ff-b726-c6d7a2ad71d6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCaWdCb3NzIiwiaWF0IjoxNjUyNDU2MjQ5LCJleHAiOjE5MjQ5MDU2MDAsInJvbGVzIjpbIkFETUlOIl19.z8RClg7GgpT4e-OjihMJbflIWiDxzrdrYNhL2HteE_A

{
  "type": "ORDINAL",
  "price": 15,
  "duration": 86400
}


### Visita al catalogo bigleitti

GET http://localhost:8082/tickets/


### Admin acquista biglietti

POST http://localhost:8082/shop/1/
X-XSRF-TOKEN: 224159f4-d4ed-41ff-b726-c6d7a2ad71d6
Content-Type: application/json
Cookie: XSRF-TOKEN=224159f4-d4ed-41ff-b726-c6d7a2ad71d6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCaWdCb3NzIiwiaWF0IjoxNjUyNDU2MjQ5LCJleHAiOjE5MjQ5MDU2MDAsInJvbGVzIjpbIkFETUlOIl19.z8RClg7GgpT4e-OjihMJbflIWiDxzrdrYNhL2HteE_A

{
  "ticketId": 1,
  "numOfTickets": 10,
  "paymentInfo": {
    "creditCardNumber": "7992-7398-713",
    "cardHolder": "Gabriele SM"
  }
}

### Test generazione message in kafka

POST http://localhost:8082/test/kafka/produce/
X-XSRF-TOKEN: 224159f4-d4ed-41ff-b726-c6d7a2ad71d6
Content-Type: application/json
Cookie: XSRF-TOKEN=224159f4-d4ed-41ff-b726-c6d7a2ad71d6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCaWdCb3NzIiwiaWF0IjoxNjUyNDU2MjQ5LCJleHAiOjE5MjQ5MDU2MDAsInJvbGVzIjpbIkFETUlOIl19.z8RClg7GgpT4e-OjihMJbflIWiDxzrdrYNhL2HteE_A

{
  "total_cost": 10,
  "billing_info": {
    "creditCardNumber": "7992-7398-713",
    "exp": "2030-01-01",
    "cvv": "123"
  }
}

### Test acquisto biglietto con pagamento a buon fine e aggiornamento dello status
#esegui solo una volta l'aggiunta di questo item al catalog (duration : 2 giorni in millis)
### Admin mette tipi di biglietti
POST http://localhost:8082/admin/tickets/
X-XSRF-TOKEN: 224159f4-d4ed-41ff-b726-c6d7a2ad71d6
Content-Type: application/json
Cookie: XSRF-TOKEN=224159f4-d4ed-41ff-b726-c6d7a2ad71d6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCaWdCb3NzIiwiaWF0IjoxNjUyNDU2MjQ5LCJleHAiOjE5MjQ5MDU2MDAsInJvbGVzIjpbIkFETUlOIl19.z8RClg7GgpT4e-OjihMJbflIWiDxzrdrYNhL2HteE_A

{
  "type": "WEEKEND-PASS",
  "price": 10,
  "duration": 172800000
}
### Admin acquista biglietti
POST http://localhost:8082/shop/1/
X-XSRF-TOKEN: 224159f4-d4ed-41ff-b726-c6d7a2ad71d6
Content-Type: application/json
Cookie: XSRF-TOKEN=224159f4-d4ed-41ff-b726-c6d7a2ad71d6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCaWdCb3NzIiwiaWF0IjoxNjUyNDU2MjQ5LCJleHAiOjE5MjQ5MDU2MDAsInJvbGVzIjpbIkFETUlOIl19.z8RClg7GgpT4e-OjihMJbflIWiDxzrdrYNhL2HteE_A

{
  "numOfTickets": 1,
  "paymentInfo": {
    "creditCardNumber": "7992-7398-713",
    "cardHolder": "Gabriele SM"
  },
  "validFrom":"2022-05-28T12:40:00Z[UTC]",
  "zid": "123"
}
###Inserisci l'order l'id restituito dalla post precedente per vederlo pending per 10 secondi
GET http://localhost:8082/orders/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCaWdCb3NzIiwiaWF0IjoxNjUyNDU2MjQ5LCJleHAiOjE5MjQ5MDU2MDAsInJvbGVzIjpbIkFETUlOIl19.z8RClg7GgpT4e-OjihMJbflIWiDxzrdrYNhL2HteE_A

###Inserisci l'order l'id restituito dalla post precedente per vederlo pending per 10 secondi
GET http://localhost:8082/orders/9000/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCaWdCb3NzIiwiaWF0IjoxNjUyNDU2MjQ5LCJleHAiOjE5MjQ5MDU2MDAsInJvbGVzIjpbIkFETUlOIl19.z8RClg7GgpT4e-OjihMJbflIWiDxzrdrYNhL2HteE_A

###Inserisci l'order l'id restituito dalla post precedente per vederlo pending per 10 secondi
GET http://localhost:8082/orders/AAAAA/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCaWdCb3NzIiwiaWF0IjoxNjUyNDU2MjQ5LCJleHAiOjE5MjQ5MDU2MDAsInJvbGVzIjpbIkFETUlOIl19.z8RClg7GgpT4e-OjihMJbflIWiDxzrdrYNhL2HteE_A


###Contatta il payment per vedere che la transazione sia stata inserita
GET http://localhost:8083/transactions/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCaWdCb3NzIiwiaWF0IjoxNjUyNDU2MjQ5LCJleHAiOjE5MjQ5MDU2MDAsInJvbGVzIjpbIkFETUlOIl19.z8RClg7GgpT4e-OjihMJbflIWiDxzrdrYNhL2HteE_A

###Ricontatta il catalog per vederlo completed
GET http://localhost:8082/orders/9/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCaWdCb3NzIiwiaWF0IjoxNjUyNDU2MjQ5LCJleHAiOjE5MjQ5MDU2MDAsInJvbGVzIjpbIkFETUlOIl19.z8RClg7GgpT4e-OjihMJbflIWiDxzrdrYNhL2HteE_A
